# ============================================================
# report/pdf_generator.py
# Generates a 7-page PDF brand intelligence report using ReportLab
# Page 1: Cover | Page 2: Executive Summary | Page 3: Sentiment
# Page 4: Negative Analysis | Page 5: Tone + Strategy
# Page 6: Recommendations | Page 7: Methodology + Limitations
# ============================================================

from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, ListFlowable, ListItem,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# ── Styles ───────────────────────────────────────────────────
_styles = getSampleStyleSheet()

_styles.add(ParagraphStyle(
    name="CoverTitle", fontSize=28, leading=34, alignment=TA_CENTER,
    textColor=colors.HexColor("#1a1a2e"), spaceAfter=20, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="CoverSubtitle", fontSize=14, leading=18, alignment=TA_CENTER,
    textColor=colors.HexColor("#555555"), spaceAfter=8,
))
_styles.add(ParagraphStyle(
    name="SectionHeading", fontSize=18, leading=22,
    textColor=colors.HexColor("#1a1a2e"), spaceAfter=14, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="SubHeading", fontSize=13, leading=16,
    textColor=colors.HexColor("#16213e"), spaceAfter=8, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="BodyText2", fontSize=10.5, leading=15,
    textColor=colors.HexColor("#333333"), spaceAfter=10, alignment=TA_LEFT,
))


# ── Page 1: Cover ───────────────────────────────────────────
def _build_cover_page(brand: str) -> list:
    elements = []
    elements.append(Spacer(1, 2.5 * inch))
    elements.append(Paragraph("Brand Intelligence Report", _styles["CoverTitle"]))
    elements.append(Paragraph(brand, _styles["CoverSubtitle"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        datetime.now().strftime("%B %d, %Y"), _styles["CoverSubtitle"]
    ))
    elements.append(Spacer(1, 2 * inch))
    elements.append(Paragraph(
        "Generated by Brand Intelligence Analyzer", _styles["CoverSubtitle"]
    ))
    elements.append(PageBreak())
    return elements


# ── Page 2: Executive Summary ──────────────────────────────
def _build_executive_summary(brand: str, strategy_report: dict) -> list:
    elements = []
    elements.append(Paragraph("Executive Summary", _styles["SectionHeading"]))

    current_strategy = strategy_report.get("current_strategy", "Not available.")
    elements.append(Paragraph(current_strategy, _styles["BodyText2"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Key Strengths", _styles["SubHeading"]))
    strengths = strategy_report.get("strengths", [])
    if strengths:
        items = [ListItem(Paragraph(s, _styles["BodyText2"])) for s in strengths]
        elements.append(ListFlowable(items, bulletType="bullet"))
    elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Key Weaknesses", _styles["SubHeading"]))
    weaknesses = strategy_report.get("weaknesses", [])
    if weaknesses:
        items = [ListItem(Paragraph(w, _styles["BodyText2"])) for w in weaknesses]
        elements.append(ListFlowable(items, bulletType="bullet"))

    elements.append(PageBreak())
    return elements


# ── Page 3: Sentiment Overview ─────────────────────────────
def _build_sentiment_page(sentiment_summary: dict) -> list:
    elements = []
    elements.append(Paragraph("Sentiment Overview", _styles["SectionHeading"]))

    data = [
        ["Metric", "Value"],
        ["Total Documents Analyzed", str(sentiment_summary.get("total_docs", "N/A"))],
        ["Positive", f"{sentiment_summary.get('positive_pct', 0)}%"],
        ["Negative", f"{sentiment_summary.get('negative_pct', 0)}%"],
        ["Neutral", f"{sentiment_summary.get('neutral_pct', 0)}%"],
    ]

    table = Table(data, colWidths=[3 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    by_source = sentiment_summary.get("by_source", {})
    if by_source:
        elements.append(Paragraph("Sentiment by Source", _styles["SubHeading"]))
        source_data = [["Source", "Positive", "Negative", "Neutral"]]
        for src, counts in by_source.items():
            source_data.append([
                ("YouTube" if src.lower() == "youtube" else src.title()),
                str(counts.get("Positive", 0)),
                str(counts.get("Negative", 0)), str(counts.get("Neutral", 0)),
            ])
        source_table = Table(source_data, colWidths=[1.5 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
        source_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(source_table)

    elements.append(PageBreak())
    return elements


# ── Page 4: Negative Analysis ──────────────────────────────
def _build_negative_analysis_page(topics_result: dict, worst_docs: list[dict]) -> list:
    elements = []
    elements.append(Paragraph("Negative Sentiment Deep Dive", _styles["SectionHeading"]))

    if topics_result.get("status") == "success":
        elements.append(Paragraph("Negative Topic Clusters", _styles["SubHeading"]))
        for topic in topics_result.get("topics", []):
            elements.append(Paragraph(
                f"<b>{topic['label']}</b> — {topic['document_count']} documents",
                _styles["BodyText2"],
            ))
    else:
        reason = topics_result.get("reason", "Insufficient data for topic modeling.")
        elements.append(Paragraph(
            f"<i>Topic modeling skipped: {reason}</i>", _styles["BodyText2"]
        ))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("Most Negative Content (Sample)", _styles["SubHeading"]))

    if worst_docs:
        data = [["Source", "Date", "Excerpt"]]
        for doc in worst_docs[:10]:
            excerpt = doc.get("text", "")[:80] + "..."
            data.append([
                doc.get("source", "N/A").title(),
                doc.get("date", "N/A"),
                excerpt,
            ])
        table = Table(data, colWidths=[0.9 * inch, 0.9 * inch, 4 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No negative content samples available.", _styles["BodyText2"]))

    elements.append(PageBreak())
    return elements


# ── Page 5: Tone + Strategy ─────────────────────────────────
def _build_tone_strategy_page(tone_result: dict, strategy_report: dict) -> list:
    elements = []
    elements.append(Paragraph("Brand Tone & Strategy Analysis", _styles["SectionHeading"]))

    elements.append(Paragraph("Brand Tone Profile", _styles["SubHeading"]))
    all_scores = tone_result.get("all_scores", [])
    if all_scores:
        data = [["Tone", "Confidence"]]
        for item in all_scores:
            data.append([item["tone"], f"{item['score'] * 100:.1f}%"])
        table = Table(data, colWidths=[2.5 * inch, 1.5 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)

    elements.append(Spacer(1, 0.25 * inch))
    elements.append(Paragraph("Strategy Analysis", _styles["SubHeading"]))
    elements.append(Paragraph(
        strategy_report.get("current_strategy", "Not available."), _styles["BodyText2"]
    ))

    elements.append(PageBreak())
    return elements


# ── Page 6: Recommendations ────────────────────────────────
def _build_recommendations_page(strategy_report: dict) -> list:
    elements = []
    elements.append(Paragraph("Recommendations", _styles["SectionHeading"]))

    recommendations = strategy_report.get("recommendations", [])
    for i, rec in enumerate(recommendations, 1):
        elements.append(Paragraph(f"{i}. {rec.get('title', '')}", _styles["SubHeading"]))
        elements.append(Paragraph(rec.get("explanation", ""), _styles["BodyText2"]))
        elements.append(Spacer(1, 0.12 * inch))

    elements.append(PageBreak())
    return elements


# ── Page 7: Methodology + Limitations ──────────────────────
def _build_methodology_page() -> list:
    elements = []
    elements.append(Paragraph("Data Sources & Methodology", _styles["SectionHeading"]))

    elements.append(Paragraph("Data Sources", _styles["SubHeading"]))
    sources_text = (
        "This report was generated using publicly available data from NewsAPI "
        "(news headlines and descriptions, last 30 days), YouTube Data API v3 "
        "(video titles, descriptions, and engagement metrics), and Wikipedia "
        "(brand background and context)."
    )
    elements.append(Paragraph(sources_text, _styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Known Limitations", _styles["SubHeading"]))
    limitations = [
        "News data is limited to the last 30 days due to free-tier API restrictions — no long-term historical analysis.",
        "YouTube analysis is based on titles and descriptions only; comments and video content are not analyzed.",
        "Topic modeling (root-cause clustering) requires a minimum of 300 negative documents to run reliably; if this threshold is not met, topic modeling is skipped.",
        "Sentiment analysis may misclassify sarcasm or highly nuanced text.",
        "This tool is scoped to large, well-known brands with substantial public coverage. Small or niche brands may yield insufficient data.",
        "Analysis is limited to English-language content.",
    ]
    items = [ListItem(Paragraph(lim, _styles["BodyText2"])) for lim in limitations]
    elements.append(ListFlowable(items, bulletType="bullet"))

    return elements


# ── Main Function — Build Full PDF ─────────────────────────
def generate_pdf_report(
    brand: str,
    output_path: str,
    sentiment_summary: dict,
    strategy_report: dict,
    tone_result: dict,
    topics_result: dict,
    worst_docs: list[dict],
) -> str:
    """
    Generates the complete 7-page brand intelligence PDF report.

    Returns:
        The output_path where the PDF was saved.
    """
    print(f"[PDFGenerator] Building PDF report for '{brand}'...")

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    story = []
    story.extend(_build_cover_page(brand))
    story.extend(_build_executive_summary(brand, strategy_report))
    story.extend(_build_sentiment_page(sentiment_summary))
    story.extend(_build_negative_analysis_page(topics_result, worst_docs))
    story.extend(_build_tone_strategy_page(tone_result, strategy_report))
    story.extend(_build_recommendations_page(strategy_report))
    story.extend(_build_methodology_page())

    doc.build(story)
    print(f"[PDFGenerator] PDF saved to {output_path}")
    return output_path


# ── Quick Test ───────────────────────────────────────────────
if __name__ == "__main__":
    test_sentiment = {
        "total_docs": 177, "positive_pct": 52.0, "negative_pct": 37.9, "neutral_pct": 10.2,
        "by_source": {
            "news": {"Positive": 60, "Negative": 45, "Neutral": 12},
            "youtube": {"Positive": 32, "Negative": 22, "Neutral": 6},
        },
    }

    test_strategy = {
        "current_strategy": "Nike pursues a sustainability and collaboration-driven strategy.",
        "strengths": ["Strong collaborations", "Sustainable product lines", "Global brand recognition"],
        "weaknesses": ["Labor practice criticism", "Legal challenges", "Limited transparency"],
        "recommendations": [
            {"title": "Enhance Transparency", "explanation": "Increase public reporting on labor practices."},
            {"title": "Resolve Legal Issues", "explanation": "Address lawsuits promptly and publicly."},
        ],
    }

    test_tone = {
        "all_scores": [
            {"tone": "Inspirational", "score": 0.957},
            {"tone": "Aggressive", "score": 0.304},
            {"tone": "Professional", "score": 0.203},
        ]
    }

    test_topics = {"status": "skipped", "reason": "Insufficient negative documents (67 found, need 300)."}

    test_worst_docs = [
        {"source": "news", "date": "2026-05-12", "text": "Customers are suing Nike over tariff refunds."},
        {"source": "youtube", "date": "2026-04-01", "text": "Disappointed with Nike's recent product quality issues."},
    ]

    generate_pdf_report(
        "Nike", "test_report.pdf", test_sentiment, test_strategy,
        test_tone, test_topics, test_worst_docs,
    )