# ============================================================
# report/pdf_generator.py
# Generates a dynamic PDF brand intelligence report using ReportLab
# ============================================================

from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, ListFlowable, ListItem, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# ── Styles ───────────────────────────────────────────────────
_styles = getSampleStyleSheet()

_styles.add(ParagraphStyle(
    name="CoverTitle", fontSize=28, leading=34, alignment=TA_CENTER,
    textColor=colors.HexColor("#1a1a2e"), spaceAfter=20, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="CoverSubtitle", fontSize=14, leading=18, alignment=TA_CENTER,
    textColor=colors.HexColor("#555555"), spaceAfter=8,
))
_styles.add(ParagraphStyle(
    name="SectionHeading", fontSize=18, leading=22,
    textColor=colors.HexColor("#1a1a2e"), spaceAfter=14, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="SubHeading", fontSize=13, leading=16,
    textColor=colors.HexColor("#16213e"), spaceAfter=8, fontName="Helvetica-Bold",
))
_styles.add(ParagraphStyle(
    name="BodyText2", fontSize=10.5, leading=15,
    textColor=colors.HexColor("#333333"), spaceAfter=10, alignment=TA_LEFT,
))
_styles.add(ParagraphStyle(
    name="CitationText", fontSize=9, leading=12,
    textColor=colors.HexColor("#666666"), spaceAfter=4, alignment=TA_LEFT, fontName="Helvetica-Oblique",
))
_styles.add(ParagraphStyle(
    name="RecommendationText", fontSize=10.5, leading=15,
    textColor=colors.HexColor("#00563B"), spaceAfter=10, alignment=TA_LEFT,
))

# ── Page 1: Cover ───────────────────────────────────────────
def _build_cover_page(brand: str) -> list:
    elements = []
    elements.append(Spacer(1, 2.5 * inch))
    elements.append(Paragraph("Brand Intelligence Report", _styles["CoverTitle"]))
    elements.append(Paragraph(brand, _styles["CoverSubtitle"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        datetime.now().strftime("%B %d, %Y"), _styles["CoverSubtitle"]
    ))
    elements.append(Spacer(1, 2 * inch))
    elements.append(Paragraph(
        "Generated by Brand Intelligence Analyzer", _styles["CoverSubtitle"]
    ))
    elements.append(PageBreak())
    return elements

# ── Page 2: Executive Summary ──────────────────────────────
def _build_executive_summary(brand: str, wikipedia_context: str, strategy_report: dict) -> list:
    elements = []
    elements.append(Paragraph("Executive Summary", _styles["SectionHeading"]))

    if wikipedia_context and wikipedia_context.strip():
        # Truncate to max 800 characters to prevent massive multi-page dumps
        trunc_context = wikipedia_context.strip()
        if len(trunc_context) > 800:
            trunc_context = trunc_context[:800].rsplit(' ', 1)[0] + "..."
            
        elements.append(Paragraph("Brand Context", _styles["SubHeading"]))
        elements.append(Paragraph(trunc_context, _styles["BodyText2"]))
        elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Current Strategy", _styles["SubHeading"]))
    current_strategy = strategy_report.get("current_strategy", "Not available.")
    elements.append(Paragraph(current_strategy, _styles["BodyText2"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Key Strengths", _styles["SubHeading"]))
    strengths = strategy_report.get("strengths", [])
    if strengths:
        items = [ListItem(Paragraph(s, _styles["BodyText2"])) for s in strengths]
        elements.append(ListFlowable(items, bulletType="bullet"))
    elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Key Weaknesses", _styles["SubHeading"]))
    weaknesses = strategy_report.get("weaknesses", [])
    if weaknesses:
        items = [ListItem(Paragraph(w, _styles["BodyText2"])) for w in weaknesses]
        elements.append(ListFlowable(items, bulletType="bullet"))

    elements.append(PageBreak())
    return elements

# ── Page 4: Sentiment Overview ─────────────────────────────
def _build_sentiment_page(sentiment_summary: dict) -> list:
    elements = []
    elements.append(Paragraph("Sentiment Overview", _styles["SectionHeading"]))

    data = [
        ["Metric", "Value"],
        ["Total Documents Analyzed", str(sentiment_summary.get("total_docs", "N/A"))],
        ["Positive", f"{sentiment_summary.get('positive_pct', 0)}%"],
        ["Negative", f"{sentiment_summary.get('negative_pct', 0)}%"],
        ["Neutral", f"{sentiment_summary.get('neutral_pct', 0)}%"],
    ]

    table = Table(data, colWidths=[3 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    by_source = sentiment_summary.get("by_source", {})
    # Filter sources that actually have data
    active_sources = {k: v for k, v in by_source.items() if any(c > 0 for c in v.values())}
    
    if active_sources:
        elements.append(Paragraph("Sentiment by Source", _styles["SubHeading"]))
        source_data = [["Source", "Positive", "Negative", "Neutral"]]
        for src, counts in active_sources.items():
            formatted_src = src.replace("_", " ").title()
            if src.lower() == "youtube":
                formatted_src = "YouTube"
            elif src.lower() == "youtube_comment":
                formatted_src = "YouTube Comment"
                
            source_data.append([
                formatted_src,
                str(counts.get("Positive", 0)),
                str(counts.get("Negative", 0)), 
                str(counts.get("Neutral", 0)),
            ])
        source_table = Table(source_data, colWidths=[1.5 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
        source_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(source_table)

    elements.append(PageBreak())
    return elements

# ── Page 5: Issues & Recommendations ───────────────────────
def _build_issues_and_recommendations(issues: list, strategy_report: dict) -> list:
    if not issues:
        return []
        
    elements = []
    elements.append(Paragraph("Issues & Recommendations", _styles["SectionHeading"]))
    
    issue_recs = strategy_report.get("issue_recommendations", [])
    
    for idx, issue in enumerate(issues):
        cluster_label = issue.get("cluster_label")
        heading = f"Cluster: {cluster_label}" if cluster_label else "Individual Complaint"
        
        elements.append(Paragraph(heading, _styles["SubHeading"]))
        
        # Add documents
        for doc in issue.get("documents", []):
            source = doc.get("source", "Unknown").replace("_", " ").title()
            date = doc.get("date", "N/A")
            text = doc.get("text", "")
            
            elements.append(Paragraph(f"Source: {source} | Date: {date}", _styles["CitationText"]))
            elements.append(Paragraph(f'"{text}"', _styles["BodyText2"]))
            elements.append(Spacer(1, 0.05 * inch))
            
        # Add recommendation
        rec_text = "No recommendation provided."
        if idx < len(issue_recs) and issue_recs[idx].get("recommendation"):
            # Replace newlines with <br/> so ReportLab renders the bullets correctly
            rec_text = issue_recs[idx].get("recommendation").replace("\n", "<br/>")
            
        elements.append(Spacer(1, 0.1 * inch))
        elements.append(Paragraph("<b>Recommended Action Plan:</b>", _styles["RecommendationText"]))
        elements.append(Paragraph(rec_text, _styles["RecommendationText"]))
        elements.append(Spacer(1, 0.3 * inch))
        
    elements.append(PageBreak())
    return elements



# ── Page 7: Methodology + Limitations ──────────────────────
def _build_methodology_page() -> list:
    elements = []
    elements.append(Paragraph("Data Sources & Methodology", _styles["SectionHeading"]))

    elements.append(Paragraph("Data Sources", _styles["SubHeading"]))
    sources_text = (
        "This report aggregates public data collected from three primary sentiment sources: NewsAPI "
        "(news headlines and descriptions, last 30 days), YouTube Data API v3 "
        "(public video comment threads), and Google Play Store app reviews. "
        "Supplementary brand-owned tone context is fetched from the brand's "
        "official YouTube channel."
    )
    elements.append(Paragraph(sources_text, _styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Known Limitations", _styles["SubHeading"]))
    limitations = [
        "News data is limited to the last 30 days due to free-tier API restrictions.",
        "Topic modeling uses a dynamic clustering threshold that skips execution if the total number of negative comments/reviews is under 15.",
        "Sentiment analysis utilizes VADER and DistilBERT, which may occasionally misclassify sarcastic or highly nuanced expressions.",
        "Play Store review tracking relies on matching the brand's primary mobile application package name.",
        "Non-English data is automatically filtered out via language detection, which may reduce volume for brands in regional markets.",
    ]
    items = [ListItem(Paragraph(lim, _styles["BodyText2"])) for lim in limitations]
    elements.append(ListFlowable(items, bulletType="bullet"))

    return elements

# ── Main Function — Build Full PDF ─────────────────────────
def generate_pdf_report(
    brand: str,
    output_path: str,
    sentiment_summary: dict,
    strategy_report: dict,
    tone_result: dict,
    wiki_data: dict,
    issues: list,
) -> str:
    """
    Generates the dynamic brand intelligence PDF report.
    Returns the output_path where the PDF was saved.
    """
    print(f"[PDFGenerator] Building PDF report for '{brand}'...")

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    story = []
    story.extend(_build_cover_page(brand))
    story.extend(_build_executive_summary(brand, wiki_data.get("general_text", ""), strategy_report))
    story.extend(_build_sentiment_page(sentiment_summary))
    story.extend(_build_issues_and_recommendations(issues, strategy_report))
    story.extend(_build_methodology_page())

    doc.build(story)
    print(f"[PDFGenerator] PDF saved to {output_path}")
    return output_path